import pygame
from enum import Enum

pygame.init()

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
WATER_SURFACE_Y = SCREEN_HEIGHT // 4
FPS = 60

SKY_COLOR = (135, 206, 235)
WATER_COLOR = (0, 51, 102)
DEEP_WATER_COLOR = (0, 30, 60)

class WeaponType(Enum):
    MISSILE = 1
    TORPEDO = 2
    DEPTH_CHARGE = 3

PLAYER_SPEED = 5
PLAYER_MAX_HEALTH = 100
MISSILE_COOLDOWN = 30
TORPEDO_COOLDOWN = 45

DESTROYER_SPEED_MIN = 1.5
DESTROYER_SPEED_MAX = 3.0
DESTROYER_HEALTH = 80
DESTROYER_SCORE = 100
DEPTH_CHARGE_COOLDOWN_MIN = 90
DEPTH_CHARGE_COOLDOWN_MAX = 150
DEPTH_CHARGE_INITIAL_COOLDOWN_MIN = 60
DEPTH_CHARGE_INITIAL_COOLDOWN_MAX = 120

ENEMY_SUB_SPEED_MIN = 1.0
ENEMY_SUB_SPEED_MAX = 2.5
ENEMY_SUB_HEALTH = 60
ENEMY_SUB_SCORE = 150
ENEMY_SUB_TORPEDO_COOLDOWN_MIN = 90
ENEMY_SUB_TORPEDO_COOLDOWN_MAX = 150
ENEMY_SUB_INITIAL_TORPEDO_COOLDOWN_MIN = 60
ENEMY_SUB_INITIAL_TORPEDO_COOLDOWN_MAX = 120

MISSILE_SPEED = 10
MISSILE_VERTICAL_SPEED = -8
MISSILE_DAMAGE = 40

TORPEDO_SPEED_PLAYER = 7
TORPEDO_SPEED_ENEMY = -5
TORPEDO_DAMAGE = 35

DEPTH_CHARGE_FALL_SPEED = 1.0
DEPTH_CHARGE_DAMAGE = 30
DEPTH_CHARGE_EXPLOSION_DAMAGE = 5
DEPTH_CHARGE_COUNT_PER_DROP = 2

EXPLOSION_MAX_TIMER = 20

DIVER_SPAWN_INTERVAL = 300
DIVER_SPEED = 1
DIVER_HEALTH_BONUS = 20
DIVER_WIDTH = 30
DIVER_HEIGHT = 40

DESTROYER_SPAWN_INTERVAL = 180
SUBMARINE_SPAWN_INTERVAL = 240
